version: '3'

services:
  ap-monitor:
    build: .
    restart: unless-stopped
    environment:
      HEARTBEAT_INTERVAL: 1
      RECOVERY_ATTEMPT_DELAY: 900
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      APMON_CONFIG: ${APMON_CONFIG}
